# Generated by Django 5.2.4 on 2025-07-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='guides',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(default='Default tour description'),
        ),
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(default='Sample Tour Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
