# Generated by Django 5.2.4 on 2025-07-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_tour_accommodation_remove_tour_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=50),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(default='X Days', max_length=50),
        ),
    ]
